website/__init__.py
from flask import Flask, session
from flask_login import LoginManager
from firebase_admin import credentials, initialize_app, firestore, auth
from flask_session import Session

cred = credentials.Certificate('website/demo_acc.json')
firebase_app = initialize_app(cred)
db = firestore.client()

def create_app():
    app = Flask(__name__)
    app.secret_key = 'SECRET KEY HERE'

    from .views import views
    from .auth_bp import auth_bp

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth_bp, url_prefix='/')
    return app

website/views.py
from difflib import get_close_matches
from sys import prefix
from weakref import ref
from flask import Flask, Blueprint, jsonify, render_template, request, flash, redirect, session, url_for
from flask_login import login_user, login_required, logout_user, current_user, UserMixin
from firebase_admin import  firestore
from flask_wtf import FlaskForm
from httplib2 import Credentials
from requests import post
from wtforms.validators import InputRequired, EqualTo
from firebase_admin import auth
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired
from firebase_admin import firestore
import firebase_admin
import random
import json


views = Blueprint('views', __name__)

@views.route("/") # Site linkine tıklandığında açılacak olan sayfa bu.
def home_page():
    return render_template('index.html')

@views.route("/main") # Kullanıcı giriş yaptıktan sonra bu sayfa açılacak.
def main_page():
    username = session['user']
    user_ref = db.collection('users').where('username', '==', username).limit(1)
    user_docs = user_ref.get()

    if not user_docs:
        return []

    user_data = user_docs[0].to_dict()
    user_games = user_data.get('games', [])
    # Kullanıcının oyun isimlerini içerecek liste
    user_game_names = [game.get('name', '') for game in user_games]

# Şimdi user_game_names listesini kullanabilirsiniz
    print(user_game_names)
    
    other_users_ref = db.collection('users').stream()

    matching_users_dict = {}
    for other_user in other_users_ref:
        other_user_data = other_user.to_dict()

        # Skip the logged-in user
        if other_user_data['username'] != username:
            other_user_games = other_user_data.get('games', [])

            # Check if any game matches with the logged-in user's games
            for game in other_user_games:
                if any(user_game['name'] == game['name'] for user_game in user_games):
                    # Add the username and game to the dictionary
                    matching_users_dict.setdefault(other_user_data['username'], []).append(game['name'])

    # Now matching_users_dict contains usernames as keys and a list of games as values
    print(matching_users_dict)    
    return render_template('user_home.html', user_data = matching_users_dict)


# Firestore bağlantısı
db = firestore.client()
@views.route('/Profile', methods = ['GET', 'POST'])
def profile():
    random_number = random.randint(1, 1000)
    if 'user' in session:
        username = session['user']
        
        # Firestore sorgusu ile kullanıcının verilerini çekme
        user_ref = db.collection('users').where('username', '==', username).limit(1)
        user_doc = user_ref.get()
    
        if user_doc:
            user_data = user_doc[0].to_dict()
            
            return render_template('Profile.html', user_data=user_data,random_number = random_number)
        else:
            # Kullanıcı belgesi bulunamadıysa başka bir işlem yapabilirsiniz
            return render_template('Profile.html', error_message='Kullanıcı bulunamadı.')
        
@views.route('/search-and-add-games', methods = ['GET', 'POST'])
def add_game():
    random_user = []
    other_users_ref = db.collection('users').stream()
    for other_user in other_users_ref:
        other_user_data = other_user.to_dict()

        # Giriş yapan kullanıcı hariç diğer kullanıcıların oyunlarını al
        random_user.append(other_user_data["username"])
        
    random_user = json.dumps(random_user)
        
    
    if 'user' in session:
        username = session['user']
        # Firestore sorgusu ile kullanıcının verilerini çekme
        user_query = db.collection('users').where('username', '==', username).limit(1)
        user_docs = user_query.get()

        if user_docs:
            user_data = user_docs[0].to_dict()

            if request.method == 'POST':
                games = request.json.get('selectedGames')             

                # Check if the user already has games
                if 'games' in user_data:
                    # If games exist, append new games to the existing list if they are not already present
                    for game in games:
                        # Check if the game is not already in the list
                        if all(existing_game['name'] != game for existing_game in user_data['games']):
                            user_data['games'].append({'name': game, 'hours': random.randint(1, 1000)})
                else:
                    # If no games exist, directly assign the games as a list of dictionaries
                    user_data['games'] = [{'name': game, 'hours': random.randint(1, 1000)} for game in games] if games else ''
                    
                    
                
                
                # Now, get the specific document reference for the user
                user_ref = db.collection('users').document(user_docs[0].id)

                if user_ref.update({'games': user_data['games']}):
                    print("buraya girdin")
                    # Flash message for success
                    

                    # Redirect to the profile page
                    

    return render_template('add_game.html',random_user = random_user)


    
@views.route('/change_password', methods=['GET', 'POST'])
def change_password():
    if 'user' in session:
        username = session['user']
        
        # Firestore sorgusu ile kullanıcının verilerini çekme
        user_ref = db.collection('users').where('username', '==', username).limit(1)
        user_doc = user_ref.get()
    
        if user_doc:
            user_data = user_doc[0].to_dict()

    return render_template('change_password.html',user_data=user_data)


db = firestore.client()

@views.route('/search', methods=['GET'])
def search():
    # Get the username from the search bar
    query = request.args.get('username')

    # Perform Firestore query
    results = perform_firestore_query(query)

    return render_template('search_results.html', results=results)

@views.route('/search_results_p/<username>', methods = ['GET', 'POST'])
def search_results_p(username):
    # Perform Firestore query to get user profile
    user_query = db.collection('users').where('username', '==', username).limit(1)
    user_docs = user_query.get()
    # Process query results
    user_data = user_docs[0].to_dict() if user_docs else None
    
    if request.method == 'POST':
        flash('Message sent succesfully.', 'success')

    return render_template('search_results_p.html', user_data=user_data)

def perform_firestore_query(prefix):
    # Firestore'dan tüm kullanıcı adlarını alın
    all_usernames = [doc.get('username') for doc in db.collection('users').stream()]

    # Kullanıcının girdiği terime benzer kullanıcı adlarını bulun
    close_matches = get_close_matches(prefix, all_usernames, n=10, cutoff=0.6)

    if not close_matches:
        # close_matches boşsa veya geçerli değilse, hata mesajı ver veya uygun bir değer ata
        return []

    # Firestore sorgusu için benzer kullanıcı adlarını kullanın
    user_query = db.collection('users').where('username', 'in', close_matches)
    user_docs = user_query.get()

    # Firestore sorgusu sonuçlarını işleyin
    results = [doc.to_dict() for doc in user_docs]

    return results

website/templates/Profile.html
{% extends "base.html" %}

{% block title %}
    Profile
{% endblock title %}

{% block content %}
<style>
  body {
    background-image: url("https://i.hizliresim.com/6gc8bli.png");
    background-size: cover;
    background-position: center;
    background-color: #1e1e1e;
    color: #d4d4d4;
    font-family: 'VT323', monospace;
    font-size: 20px;
}

button {
  background-color: #585EFF;
}

div.container {
  margin-top: 70px;
  min-height: 80vh;
}

div.alert {
  margin-top: 10px;
}

.profile-container {
  background-color: rgba(42, 42, 42, 0.8);
  color: #d4d4d4;
  padding: 20px;
  border-radius: 8px;
  width: 45%;
  margin: auto;
  text-align: left;
  backdrop-filter: blur(10px); 
  border: 1px solid rgba(255, 255, 255, 0.2); /* Border color for contrast */
}

.card {
  border: 1px solid rgba(255, 255, 255, 0.2); /* Border color for contrast */
  background-color: rgba(42, 42, 42, 0.8);
  backdrop-filter: blur(10px); /* Glass effect */
  margin-top: 20px;
  min-height: 60vh; /* Minumum yükseklik belirlenir */
  overflow-y: auto; /* İçerik artarsa scroll bar ekle */
}

.card-header {
  border: 1px solid rgba(255, 255, 255, 0.2); /* Border color for contrast */
  backdrop-filter: blur(10px); /* Glass effect */
  background-color: #585EFF;
  color: #fff;
  text-align: center;
}

.card-body {
  background-color: #fff;
  color: #333;
}

.center-button {
  text-align: center;
  margin-top: 20px;
}

.btn-primary {
  background-color: #585EFF;
  border: 1px solid #585EFF;
  width: 50%;
  margin-bottom: 10px;
}

.btn-primary:hover {
  background-color: #8488F4;
}

.forgot-password-link {
  background-color: #4CAF50;
  border: 1px solid #4CAF50;
  width: 50%;
  margin-top: 20px;
  text-align: center;

    
    }

    #forgotPasswordForm {
      width: 44%;
      text-align: center;
      margin: auto;
      padding: 20px;
      background-color: rgba(42, 42, 42, 0.8);
      border-radius: 5px;
      margin-top: 20px;
      display: none;
      backdrop-filter: blur(10px); /* Glass effect */
      border: 1px solid rgba(255, 255, 255, 0.2); /* Border color for contrast */
    }

</style>


 

<div class="container">
  <div class="row">
    <div class="col">
      <div class="profile-container text-center">
        <h1>User Profile</h1>
        <div class="card">
          <div class="card-header">
            {{ user_data.username }}
          </div>
          <div class="card-body">
            <h5 class="card-title">Welcome To Your Profile Page!</h5>
            <p class="card-text">
              <p><strong>Username:</strong> {{ user_data.username }}</p>
              <p><strong>Email:</strong> {{ user_data.email }}</p>
              <p><strong>Gender:</strong> {{ user_data.gender if 'gender' in user_data else 'Other' }}</p>
              <p><strong>Games You Play:</strong></p>
              <ul>
                  {% for game in user_data.games %}
                      <li>{{ game.name }}: {{ game.hours }} hours</li>
                  {% endfor %}
              </ul>
            </p>
          </div>
        </div>

        <div class="center-button">
          <button class="btn btn-primary" onclick="window.location.href='/search-and-add-games'">Search & Add Games</button>
          <div class="btn btn-primary" onclick="showForgotPasswordForm()">Change Password</div>
        </div>

      </div>  
    </div>
  </div>
</div>

   <!-- Forgot password form -->
   <div id="forgotPasswordForm">
    <h3>Change Password</h3>
    <div class="form-group">
      <label for="forgotEmail">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="forgotEmail"
        name="forgotEmail"
        placeholder="Enter your email"
      />
    </div>
    <br />
    <button type="button" class="btn btn-primary" onclick="submitForgotPasswordForm()">Change Password</button>
  </div>

    <!-- Add Firebase JavaScript SDK -->
<script src="https://www.gstatic.com/firebasejs/8.8.0/firebase.js"></script>
<script>
  var firebaseConfig = {
    'apiKey': "AIzaSyBUVGM_OnNbu_K8lLykM5T-Tu31mIUAgkw",
    'authDomain': "prepair-demo.firebaseapp.com",
    'projectId': "prepair-demo",
    'storageBucket': "prepair-demo.appspot.com",
    'messagingSenderId': "718275532446",
    'appId': "1:718275532446:web:0f85dd84fb87cc83fd0d8f",
    'measurementId': "G-3DLX53HNSV",
    'databaseURL' : ''
  };
  firebase.initializeApp(firebaseConfig);

</script>


  <script>
    function showForgotPasswordForm() {
      var forgotPasswordForm = document.getElementById('forgotPasswordForm');
      if (forgotPasswordForm.style.display === 'none') {
        forgotPasswordForm.style.display = 'block';
      } else {
        forgotPasswordForm.style.display = 'none';
      }
    }

    function submitForgotPasswordForm() {
      var email = document.getElementById('forgotEmail').value;

      // E-posta adresini Firebase'e göndererek şifre sıfırlama emaili isteği yap
      var auth = firebase.auth();
      document.getElementById('forgotEmail').value = 'E-mail successfully sent!';
      
      auth.sendPasswordResetEmail(email)
        .then(function () {
          // Şifre sıfırlama emaili başarıyla gönderildi
          console.log('Password reset email sent');
      // Şifremi unuttum formunu gönderdikten sonra gizle
          document.getElementById('forgotPasswordForm').style.display = 'none';
        })
        .catch(function (error) {
      // Hata oluştuğunda işlemler burada yapılacak
          console.error('Error sending password reset email:', error);
        });
    }
  </script>

{% endblock content %}

website/templates/add_game.html
{% extends "base.html" %}

{% block title %}
  Search & Add Games
{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Games</title>
    <!-- Include the Firebase SDK -->
    <script defer src="https://www.gstatic.com/firebasejs/9.0.2/firebase-app-compat.js"></script>
    <script defer src="https://www.gstatic.com/firebasejs/9.0.2/firebase-firestore-compat.js"></script>
</head>

<body>

    <h1 style="text-align: center;">Search & Add Games To Your Profile</h1>

    <!-- Add the search bar -->
    <div id="searchContainer" style="text-align: center;">
        <input type="text" id="searchInput" placeholder="Search...">
    </div>

    <div id="gameContainer"></div>
    <div id="clickedGamesList"></div>

    <!-- Add the submit button -->
    <button id="submitGamesButton">Submit Selected Games</button>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const firebaseConfig = {
                apiKey: "AIzaSyBUVGM_OnNbu_K8lLykM5T-Tu31mIUAgkw",
                authDomain: "prepair-demo.firebaseapp.com",
                projectId: "prepair-demo",
                storageBucket: "prepair-demo.appspot.com",
                messagingSenderId: "718275532446",
                appId: "1:718275532446:web:0f85dd84fb87cc83fd0d8f"
            };

            firebase.initializeApp(firebaseConfig);
            
            var jsonString = '{{ random_user|safe }}';
            var random_user = JSON.parse(jsonString);
            const db = firebase.firestore();
            const gamesCollection = db.collection('games');
            const gameContainer = document.getElementById('gameContainer');
            const clickedGamesList = document.getElementById('clickedGamesList');
            const clickedGames = new Set();

            function renderGamesByGenre(games) {
                const gamesByGenre = {};

                games.forEach(game => {
                    const genre = game.data().genre;
                    if (!gamesByGenre[genre]) {
                        gamesByGenre[genre] = [];
                    }
                    gamesByGenre[genre].push(game.data());
                });

                for (const genre in gamesByGenre) {
                    const columnDiv = document.createElement('div');
                    columnDiv.className = 'genreColumn';

                    const titleDiv = document.createElement('div');
                    titleDiv.className = 'genreTitle';
                    titleDiv.textContent = `Genre: ${genre}`;
                    columnDiv.appendChild(titleDiv);

                    const ul = document.createElement('ul');
                    gamesByGenre[genre].forEach(game => {
                        var randomItem = random_user[Math.floor(Math.random() * random_user.length)]
                        const li = document.createElement('li');
                        const button = document.createElement('button');
                        button.textContent = game.name + " - Most Played by " + randomItem;
                        button.className = 'gameButton'; // Added class for styling consistency

                        button.addEventListener('click', () => {
                            if (!clickedGames.has(game.name)) {
                                clickedGames.add(game.name);
                                const listItem = document.createElement('div');
                                listItem.textContent = game.name;
                                listItem.className = 'clickedGameItem'; // Added class for styling consistency

                                listItem.addEventListener('click', () => {
                                    clickedGames.delete(game.name);
                                    listItem.remove();
                                });

                                clickedGamesList.appendChild(listItem);
                            }
                        });

                        li.appendChild(button);
                        ul.appendChild(li);
                    });

                    columnDiv.appendChild(ul);
                    gameContainer.appendChild(columnDiv);
                }
            }

            gamesCollection.get().then(querySnapshot => {
                const games = querySnapshot.docs;
                renderGamesByGenre(games);
            }).catch(error => {
                console.error('Error getting games: ', error);
            });

            // Get the search input element
            const searchInput = document.getElementById('searchInput');

            // Add an input event listener to the search input
            searchInput.addEventListener('input', function () {
                const searchTerm = searchInput.value.toLowerCase();

                // Loop through all game buttons and highlight based on the search term
                document.querySelectorAll('.gameButton').forEach(function (button) {
                    const gameName = button.textContent.toLowerCase();
                    if (gameName.includes(searchTerm)) {
                        button.style.backgroundColor = '#585EFF';
                        button.style.color = '#fff' // Highlight color
                    } else {
                        button.style.backgroundColor = ''; 
                        button.style.color = '#d4d4d4'; // Reset background color
                    }
                });

                if (searchTerm === '') {
                    document.querySelectorAll('.gameButton').forEach(function (button) {
                        button.style.backgroundColor = '';
                        button.style.color = '#d4d4d4'; // Reset background color
                    });
                }

            });
            
            // Get the submit button element
            const submitGamesButton = document.getElementById('submitGamesButton');

            // Add a click event listener to the submit button
            submitGamesButton.addEventListener('click', function () {
                // Convert the clickedGames Set to an array for easier handling
                const selectedGamesArray = Array.from(clickedGames);

                // Perform a POST request to the backend with the selected games
                fetch('/search-and-add-games', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ selectedGames: selectedGamesArray }),
                })
                .then(response => response.json())
                .then(data => {
                    console.log('Games submitted successfully:', data);
                    // Optionally, you can reset the clickedGames Set and update the UI accordingly
                    clickedGames.clear();
                    clickedGamesList.innerHTML = ''; // Clear the clicked games list
                })
                .catch(error => {
                    clickedGames.clear();
                    clickedGamesList.innerHTML = ''; // Clear the clicked games list,            
                });
            });
        });
    </script>

    <style>
        body {
            background-image: url("https://i.hizliresim.com/6gc8bli.png");
            background-size: cover;
            background-position: center;
            color: #d4d4d4;
            font-family: 'VT323', monospace;
            margin: 0;
            background-attachment: fixed; 
        }
        
        #gameContainer {
            display: flex;
            color: #d4d4d4; /* Updated text color */
            font-family: 'VT323', monospace;
            margin: 0 auto; 
            display: flex;
            flex-wrap: wrap; /* Allow columns to wrap to the next line if needed */
            justify-content: space-around;
        }
    
        .genreColumn {
            margin: 20px;
            padding: 10px;
            border: 1px solid #CB34A5; /* Updated border color */
            background-color: rgba(42, 42, 42, 0.8);
            color: #d4d4d4; /* Updated text color */
            text-align: left; 
            max-height: 70vh; /* Set a specific height for each genre column */
            overflow-y: auto;
            overflow-x: hidden;,
            white-space: nowrap; 
        }

        .genreColumn::-webkit-scrollbar {
            width: 5px;
            background-color: transparent;
        }
    
        .genreTitle {
    
            margin-bottom: 10px;
            color: #CB34A5; /* Updated text color */
        }
    
        button {
            margin-bottom: 5px;
            cursor: pointer;
            background-color: #CB34A5; /* Updated background color */
            color: #fff; /* Updated text color */
        }
    
        .gameButton {
            width: auto; 
            border: 1px solid #CB34A5; /* Updated border color */
            padding: 5px;
            background-color: #2c2c2c; /* Updated background color */
            color: #d4d4d4; /* Updated text color */
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        #submitGamesButton {
            display: block;
            margin: 20px auto; /* Set top and bottom margin to 20px and left-right margin to auto for centering */
            padding: 10px;
            background-color: #CB34A5; /* Updated background color */
            color: #fff; /* Updated text color */
            cursor: pointer;
            border: none;
            border-radius: 5px;
        }
    
        #clickedGamesList {
            margin-top: 20px;
            cursor: pointer;
        }
    
        .clickedGameItem {
            margin-bottom: 5px;
            border: 1px solid #4CAF50; /* Updated border color */
            padding: 5px;
            background-color: #fff; /* Updated background color */
            color: #333; /* Updated text color */
        }
    
        #searchContainer {
            margin-bottom: 20px;
        }
    
        #searchInput {
            padding: 5px;
            width: 200px;
        }
    </style>

</body>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=VT323&display=swap">

  <style>
    body {
      background-color: #ffffff;
      color: #d4d4d4;
      font-family: 'VT323', monospace;
      font-size: 20px;
      background-attachment: fixed; 
    }

    nav.navbar {
      background-color: #141414;
    }

    nav.navbar a.nav-link {
      color: #d4d4d4;
    }

    nav.navbar a.nav-link:hover {
      color: #4CAF50;
    }

    div.container {
      margin-top: 70px;
    }

    div.alert {
      margin-top: 10px;
    }
    ::-webkit-scrollbar {
      width: 8px; /* Adjust the width as needed */
    }
    
    /* Scrollbar track */
    ::-webkit-scrollbar-track {
      background-color: #f1f1f1;
    }
    
    /* Scrollbar thumb */
    ::-webkit-scrollbar-thumb {
      background-color: #888;
    }
    
    /* Hover effect on scrollbar thumb */
    ::-webkit-scrollbar-thumb:hover {
      background-color: #555;
    }
    
  </style>

  <title>{% block title %}Home{% endblock %}</title>
</head>
<body>



  <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav">
        {% if 'user' in session %}
          <a class="nav-item nav-link" id="home" href="/main">&nbsp;Home&nbsp;</a>
          <a class="nav-item nav-link" id="Profile" href="/Profile">&nbsp;Profile&nbsp;</a>
          <div class="ml-auto"> <!-- Apply ml-auto to a separate div -->
      <a class="nav-item nav-link" id="logout" href="/logout">&nbsp;Logout&nbsp;</a>
    </div>
   <form
   method="GET" action="{{ url_for('views.search') }}">
    <input type="text" name="username" placeholder="Search For User">
    <button type="submit" class="search-button">&nbsp;Search&nbsp;</button>
</form>

        {% else %}
          <a class="nav-item nav-link" id="login" href="/login">&nbsp;Login&nbsp;</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">&nbsp;Sign Up&nbsp;</a>
          <a class="nav-item nav-link" id="back" href="/">Welcome Page</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class="position-fixed fixed-top" style="width: 100%; top: 70px;">
          {% for category, message in messages %}
            {% if category == 'error' %}
              <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% else %}
              <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

website/templates/search_results.html
{% extends "base.html" %}

{% block title %}
  Search Results
{% endblock %}

{% block content %}
<style> /* Stil dosyası (style.css) */

body {
    background-image: url("https://i.hizliresim.com/6gc8bli.png");
    background-size: cover;
    background-position: center;
    font-family: 'VT323', monospace;
    background-color: #f4f4f4;
    margin: 0;
    padding: 0;
    display: flex;
    height: 100vh;
    
}

button {
    background-color: #585EFF;
  }

.search-results-container {
    margin: 0 auto:
    max-width: 500px;
    width: 100%;
    background-color: rgba(42, 42, 42, 0.8);
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    margin-top: 50px; /* Sayfanın üstünden biraz aşağıda başlasın */
    backdrop-filter: blur(1px); 
    border: 1px solid rgba(255, 255, 255, 0.2); /* Border color for contrast */
}

h1 {
    color: #21EF80;
    text-align: center;
}

.result-list {
    list-style: none;
    padding: 0;
}

.result-list li {
    margin: 10px 0;
}

.result-list a {
    text-decoration: none;
    color: #585EFF;
    font-weight: bold;
    font-size: 18px;
    transition: color 0.3s ease;
    display: block;
}

.result-list a:hover {
    color: #8488F4;
}

</style>
    <div class="search-results-container text-center">
        <h1>Search Results</h1>

        {% if results %}
            <ol class="result-list">
                {% for result in results %}
                    <li>
                        <a href="{{ url_for('views.search_results_p', username=result.username) }}">
                            {{ result.username }}
                        </a>
                    </li>
                {% endfor %}
            </ol>
        {% else %}
            <p>No results found.</p>
        {% endif %}
    </div>

{% endblock content %}
    

website/templates/user_home.html
{% extends "base.html" %}

{% block title %}
  Home
{% endblock %}

{% block content %}
  <style>
    body {
      background-image: url("https://i.hizliresim.com/6gc8bli.png");
      background-size: cover;
      background-position: center;
      background-color: #1e1e1e;
      color: #d4d4d4;
      font-family: 'VT323', monospace;
      display: flex;
      flex-direction: column;
      align-items: center;
      height: 100vh;
      margin: 0;
    }

    button {
      background-color: #FFD707;
    }
    

    h1 {
      text-align: center;
      color: #FFD707;
      font-size: 50px;
      margin-top: 50px;
    }

    p {
      text-align: center;
      font-size: 35px;
    }

    ul {
      text-align: center;
      list-style:none;
      font-size: 25px;
    }

  </style> 

  <h1>Welcome to your home page, {% if 'user' in session %}{{ session['user'] }}{% else %}Guest{% endif %}!</h1>
  <p>You matched with these users based on the games you play:
    <ul>
        {% for username, games in user_data.items() %}
            <li>
                <a href="{{ url_for('views.search_results_p', username=username) }}">
                   <span style="color: #585EFF;"> - {{ username }} </span> 
                    <span style="color: #fff;"> plays </span> 
                    <span style="color: #8488F4">{{ ', '.join(games) }}</span>
                </a>
            </li>
        {% endfor %}
    </ul>
</p>


{% endblock %}